# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cacb20950c145dfcc946d8a07a15bd7293926280ee1d9bd0c3a3e3496712e5c740e4793d11ea78a3bc428397c6c641ce50b3901d551784831f5206ba3389b761

test:
  secret_key_base: 043c1fe1da0104527eef214e656ec69d668b1ee117c94afb7c8c74596c716c333a7400a4c586255daa7379cf0159ad883d18819a1029b0b5e88f4b7320ded51a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
